#!/usr/bin/env bash
#######################################################
# post install script for Rhel 10 hardening for image builder
# blueprint for hybrid cloude console
#
#
#
#
#
#       CIS benchmark level 2 server
#
#
#
#
#
########################################################

### create a new aide database
